version: 1.0.{build}
os: Visual Studio 2015
shallow_clone: true
install:
- cmd: echo %DNX_BUILD_VERSION%
- cmd: echo %WEBPROJ_ENABLEBETA7RENAMES%
- cmd: set PATH=C:\Program Files (x86)\MSBuild\14.0\Bin;%PATH%
- cmd: dnvm update-self
- cmd: dnvm install 1.0.0-beta6
- cmd: dnu restore --quiet --parallel
build:
  project: AppveyorAspNet5Build.sln
  verbosity: minimal
artifacts:
  - path: '**\*.nupkg'
environment:
  DNX_BUILD_VERSION: beta6-%APPVEYOR_BUILD_NUMBER%
init:
- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#init:
#- ps: iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
#on_finish:
#- ps: $blockRdp = $true; iex ((new-object net.webclient).DownloadString('https://raw.githubusercontent.com/appveyor/ci/master/scripts/enable-rdp.ps1'))
